# Select image from https://hub.docker.com/r/_/php/
image: php:5.5

# Select what we should cache
cache:
  paths:
  - vendor/

# Services
services:
  - mysql

# Variables
variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "1"
  # Configure mysql service https://hub.docker.com/_/mysql/
  MYSQL_DATABASE: "testdb"
  MYSQL_ROOT_PASSWORD: "rootpass"

# Install dependencies
before_script:
  # Install php extensions
  - apt-get update -y
  - apt-get install -y git libicu-dev libcurl4-openssl-dev libmcrypt-dev zlib1g-dev
  - docker-php-ext-install iconv intl curl mbstring mcrypt pdo_mysql zip
  - apt-get autoremove -y && apt-get clean all
  # Install composer
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  - php composer.phar run-script post-create-project-cmd
  # Set mysql connection parameters
  - sed -i "s/__DB_HOST__/mysql/g;s/__DB_NAME__/testdb/g;s/__DB_USER__/root/g;s/__DB_PASS__/rootpass/g" app/config/app.php

# We test PHP5.5 (the default) with MySQL
test:php55:
  script:
    - php vendor/bin/phpcs
    - php vendor/bin/phpunit

# We test PHP5.6 with MySQL
test:php56:
  image: php:5.6
  script:
    - php vendor/bin/phpcs
    - php vendor/bin/phpunit

# We test PHP7.0 with MySQL
test:php70:
  image: php:7.0
  script:
    - php vendor/bin/phpcs
    - php vendor/bin/phpunit

# We test PHP7.1 with MySQL
test:php71:
  image: php:7.1
  script:
    - php vendor/bin/phpcs
    - php vendor/bin/phpunit